# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: TOPJoint dev CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: [self-hosted, dev]


    steps:
    - uses: actions/checkout@v3
    - uses: szenius/set-timezone@v1.2
      with:
          timezoneLinux: "Africa/Nairobi"
    - name: Set dotenv variable
      run: |
         export NODE_ENV=development
         export DOTENV_KEY="${{ secrets.DOTENV_KEY_DEV }}"
    - run: npm ci
    - run: npm run build --if-present
    - name: Start application
      run: pm2 describe topjoint_api-development &> /dev/null && pm2 reload ecosystem.config.js --env development --update-env || pm2 start ecosystem.config.js --env development 
