# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: TOPJoint prod CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [self-hosted, main]


    steps:
    - uses: actions/checkout@v3
    - uses: szenius/set-timezone@v1.2
      with:
          timezoneLinux: "Africa/Nairobi"
    - name: Set dotenv variable
      run: |
         export NODE_ENV=production
         export DOTENV_KEY="${{ secrets.DOTENV_KEY }}"
    - run: npm ci
    - run: npm run build --if-present
    - name: Start application
      run: pm2 describe topjoint_api-production &> /dev/null && pm2 reload npm --name topjoint_api-production --env production --update-env -- run start || pm2 start npm --name topjoint_api-production --env production -- run start
